# This is a basic workflow to help you get started with Actions

name: Simple listing file

# Controls when the workflow will run
on: push
jobs:
  simple job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple command
        run: ls -l
        
  
